name: project_b
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  dartz: ^0.10.1
  intl: ^0.17.0
  hive: ^2.2.3
  http: ^0.13.4
  provider: ^6.0.2
  flutter_svg: ^1.0.3
  hive_flutter: ^1.1.0
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.4.0
  easy_localization: ^3.0.0
  firebase_database: ^9.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0


flutter:


  uses-material-design: true

  assets:
    - assets/language/
    - assets/icons/
    - assets/images/
    - assets/